# # To boot the app run the following:
# # docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    volumes:
      - "./auto_gpt_workspace:/home/appuser/auto_gpt_workspace"
    # profiles: ["exclude-from-up"]

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
